/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  // theme: {
  //   extend: {
  //     fontSize: {
  //       // Text Sizes
  //       xs: ['var(--text-xs)', { lineHeight: 'var(--leading-xs)' }],
  //       sm: ['var(--text-sm)', { lineHeight: 'var(--leading-sm)' }],
  //       md: ['var(--text-md)', { lineHeight: 'var(--leading-md)' }],
  //       lg: ['var(--text-lg)', { lineHeight: 'var(--leading-lg)' }],
  //       xl: ['var(--text-xl)', { lineHeight: 'var(--leading-xl)' }],

  //       // Display Sizes
  //       'display-xs': [
  //         'var(--text-display-xs)',
  //         { lineHeight: 'var(--leading-display-xs)' },
  //       ],
  //       'display-sm': [
  //         'var(--text-display-sm)',
  //         { lineHeight: 'var(--leading-display-sm)' },
  //       ],
  //       'display-md': [
  //         'var(--text-display-md)',
  //         { lineHeight: 'var(--leading-display-md)' },
  //       ],
  //       'display-lg': [
  //         'var(--text-display-lg)',
  //         { lineHeight: 'var(--leading-display-lg)' },
  //       ],
  //       'display-xl': [
  //         'var(--text-display-xl)',
  //         { lineHeight: 'var(--leading-display-xl)' },
  //       ],
  //       'display-2xl': [
  //         'var(--text-display-2xl)',
  //         { lineHeight: 'var(--leading-display-2xl)' },
  //       ],
  //       'display-3xl': [
  //         'var(--text-display-3xl)',
  //         { lineHeight: 'var(--leading-display-3xl)' },
  //       ],
  //     },
  //     lineHeight: {
  //       // Text Line Heights
  //       xs: 'var(--leading-xs)',
  //       sm: 'var(--leading-sm)',
  //       md: 'var(--leading-md)',
  //       lg: 'var(--leading-lg)',
  //       xl: 'var(--leading-xl)',

  //       // Display Line Heights
  //       'display-xs': 'var(--leading-display-xs)',
  //       'display-sm': 'var(--leading-display-sm)',
  //       'display-md': 'var(--leading-display-md)',
  //       'display-lg': 'var(--leading-display-lg)',
  //       'display-xl': 'var(--leading-display-xl)',
  //       'display-2xl': 'var(--leading-display-2xl)',
  //       'display-3xl': 'var(--leading-display-3xl)',
  //     },
  //   },
  // },
  safelist: [
    // Base text sizes
    'text-xs',
    'text-sm',
    'text-md',
    'text-lg',
    'text-xl',
    'text-2xl',
    'text-display-xs',
    'text-display-sm',
    'text-display-md',
    'text-display-lg',
    'text-display-xl',
    'text-display-2xl',
    'text-display-3xl',

    // Base line heights
    'leading-xs',
    'leading-sm',
    'leading-md',
    'leading-lg',
    'leading-xl',
    'leading-2xl',
    'leading-display-xs',
    'leading-display-sm',
    'leading-display-md',
    'leading-display-lg',
    'leading-display-xl',
    'leading-display-2xl',
    'leading-display-3xl',

    // SM breakpoint
    'sm:text-xs',
    'sm:text-sm',
    'sm:text-md',
    'sm:text-lg',
    'sm:text-xl',
    'sm:text-2xl',
    'sm:text-display-xs',
    'sm:text-display-sm',
    'sm:text-display-md',
    'sm:text-display-lg',
    'sm:text-display-xl',
    'sm:text-display-2xl',
    'sm:text-display-3xl',
    'sm:leading-xs',
    'sm:leading-sm',
    'sm:leading-md',
    'sm:leading-lg',
    'sm:leading-xl',
    'sm:leading-2xl',
    'sm:leading-display-xs',
    'sm:leading-display-sm',
    'sm:leading-display-md',
    'sm:leading-display-lg',
    'sm:leading-display-xl',
    'sm:leading-display-2xl',
    'sm:leading-display-3xl',

    // MD breakpoint
    'md:text-xs',
    'md:text-sm',
    'md:text-md',
    'md:text-lg',
    'md:text-xl',
    'md:text-2xl',
    'md:text-display-xs',
    'md:text-display-sm',
    'md:text-display-md',
    'md:text-display-lg',
    'md:text-display-xl',
    'md:text-display-2xl',
    'md:text-display-3xl',
    'md:leading-xs',
    'md:leading-sm',
    'md:leading-md',
    'md:leading-lg',
    'md:leading-xl',
    'md:leading-2xl',
    'md:leading-display-xs',
    'md:leading-display-sm',
    'md:leading-display-md',
    'md:leading-display-lg',
    'md:leading-display-xl',
    'md:leading-display-2xl',
    'md:leading-display-3xl',

    // LG breakpoint (THIS IS THE IMPORTANT ONE!)
    'lg:text-xs',
    'lg:text-sm',
    'lg:text-md',
    'lg:text-lg',
    'lg:text-xl',
    'lg:text-2xl',
    'lg:text-display-xs',
    'lg:text-display-sm',
    'lg:text-display-md',
    'lg:text-display-lg',
    'lg:text-display-xl',
    'lg:text-display-2xl',
    'lg:text-display-3xl',
    'lg:leading-xs',
    'lg:leading-sm',
    'lg:leading-md',
    'lg:leading-lg',
    'lg:leading-xl',
    'lg:leading-2xl',
    'lg:leading-display-xs',
    'lg:leading-display-sm',
    'lg:leading-display-md',
    'lg:leading-display-lg',
    'lg:leading-display-xl',
    'lg:leading-display-2xl',
    'lg:leading-display-3xl',

    // XL breakpoint
    'xl:text-xs',
    'xl:text-sm',
    'xl:text-md',
    'xl:text-lg',
    'xl:text-xl',
    'xl:text-2xl',
    'xl:text-display-xs',
    'xl:text-display-sm',
    'xl:text-display-md',
    'xl:text-display-lg',
    'xl:text-display-xl',
    'xl:text-display-2xl',
    'xl:text-display-3xl',
    'xl:leading-xs',
    'xl:leading-sm',
    'xl:leading-md',
    'xl:leading-lg',
    'xl:leading-xl',
    'xl:leading-2xl',
    'xl:leading-display-xs',
    'xl:leading-display-sm',
    'xl:leading-display-md',
    'xl:leading-display-lg',
    'xl:leading-display-xl',
    'xl:leading-display-2xl',
    'xl:leading-display-3xl',

    // 2XL breakpoint
    '2xl:text-xs',
    '2xl:text-sm',
    '2xl:text-md',
    '2xl:text-lg',
    '2xl:text-xl',
    '2xl:text-2xl',
    '2xl:text-display-xs',
    '2xl:text-display-sm',
    '2xl:text-display-md',
    '2xl:text-display-lg',
    '2xl:text-display-xl',
    '2xl:text-display-2xl',
    '2xl:text-display-3xl',
    '2xl:leading-xs',
    '2xl:leading-sm',
    '2xl:leading-md',
    '2xl:leading-lg',
    '2xl:leading-xl',
    '2xl:leading-2xl',
    '2xl:leading-display-xs',
    '2xl:leading-display-sm',
    '2xl:leading-display-md',
    '2xl:leading-display-lg',
    '2xl:leading-display-xl',
    '2xl:leading-display-2xl',
    '2xl:leading-display-3xl',

    // Font weights (all breakpoints)
    'font-thin',
    'font-extralight',
    'font-light',
    'font-normal',
    'font-medium',
    'font-semibold',
    'font-bold',
    'font-extrabold',
    'font-black',
    'sm:font-thin',
    'sm:font-extralight',
    'sm:font-light',
    'sm:font-normal',
    'sm:font-medium',
    'sm:font-semibold',
    'sm:font-bold',
    'sm:font-extrabold',
    'sm:font-black',
    'md:font-thin',
    'md:font-extralight',
    'md:font-light',
    'md:font-normal',
    'md:font-medium',
    'md:font-semibold',
    'md:font-bold',
    'md:font-extrabold',
    'md:font-black',
    'lg:font-thin',
    'lg:font-extralight',
    'lg:font-light',
    'lg:font-normal',
    'lg:font-medium',
    'lg:font-semibold',
    'lg:font-bold',
    'lg:font-extrabold',
    'lg:font-black',
    'xl:font-thin',
    'xl:font-extralight',
    'xl:font-light',
    'xl:font-normal',
    'xl:font-medium',
    'xl:font-semibold',
    'xl:font-bold',
    'xl:font-extrabold',
    'xl:font-black',
    '2xl:font-thin',
    '2xl:font-extralight',
    '2xl:font-light',
    '2xl:font-normal',
    '2xl:font-medium',
    '2xl:font-semibold',
    '2xl:font-bold',
    '2xl:font-extrabold',
    '2xl:font-black',

    // Pattern for arbitrary values like text-[48px]
    {
      pattern: /^text-\[.+\]$/,
      variants: ['sm', 'md', 'lg', 'xl', '2xl'],
    },
    {
      pattern: /^leading-\[.+\]$/,
      variants: ['sm', 'md', 'lg', 'xl', '2xl'],
    },
  ],
  plugins: [],
};
